---

name: ci
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        go_version:
          - '1.11.x'
          - '1.12.x'
          - '1.13.x'
          - '1.14.x'
        os:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
      - name: install
        run: |
          go get -v all
      - name: test
        run: |
          go test -race -cover ./...
      - name: lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
